language: python

sudo: required
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

python:
  - 2.7
  - 3.8

install:
  - pip install --quiet coveralls
  - pip install --quiet nose
  - pip install --quiet coverage
  - pip install --quiet numpy
  - pip install --quiet scipy
  - pip install --quiet atomneb
  - python setup.py install

script: 
  - nosetests --with-coverage --cover-package=pyequib

after_success:
  - coveralls
